language: cpp
cache:
 ccache: true
 directories:
    - /home/travis/toolchain

matrix:
  include:

  # Ubuntu, g++-8
  - os: linux
    dist: trusty
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
          - libboost1.55-all-dev
          - libssl-dev
          - g++-8
          - gcc-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - LABEL="linux"
    - _DEPLOYABLE="true"
    - STRIP="strip"

  # Ubuntu, g++-7
  - os: linux
    dist: trusty
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
          - libboost1.55-all-dev
          - libssl-dev
          - g++-7
          - gcc-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LABEL="linux-g++-7"
    - STRIP="strip"

  # Ubuntu, clang-6
  - os: linux
    dist: trusty
    compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        packages:
          - libboost1.55-all-dev
          - libssl-dev
          - clang-6.0
          - libstdc++-7-dev
    env:
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - LABEL="linux-clang-6"
    - STRIP="strip"

  # OSX, clang
  - os: osx
    osx_image: xcode10
    compiler: clang
    env:
    - MATRIX_EVAL="CC=/usr/local/opt/llvm@8/bin/clang && CXX=/usr/local/opt/llvm@8/bin/clang++"
    - LABEL="osx"
    - _DEPLOYABLE="true"
    - STRIP="strip"

  # Arm (aarch64) cross compile
  - os: linux
    dist: trusty
    env:
    - MATRIX_EVAL="CC=aarch64-linux-gnu-gcc && CXX=aarch64-linux-gnu-g++"
    - LABEL="aarch64"
    - _DEPLOYABLE="true"
    - STRIP="aarch64-linux-gnu-strip"

before_install:
- eval $MATRIX_EVAL

install:
# Need to uninstall oclint to get newer gcc installed https://github.com/travis-ci/travis-ci/issues/8826
- if [[ "${LABEL:0:3}" == "osx" ]]; then brew cask uninstall --force oclint || true ; fi

# Need a newer version of llvm to link against to get std::filesystem / std::experimental::filesystem
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install llvm@8 || travis_retry brew upgrade llvm@8 ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew link --force llvm@8 ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then ln -s /usr/local/opt/llvm@8 /usr/local/opt/llvm ; fi

# Need to make sure that we have openssl installed
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install openssl || travis_retry brew upgrade openssl ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then brew link --force openssl ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then ln -s /usr/local/opt/openssl/include/openssl /usr/local/include ; fi

# Neeed to install ccache
- if [[ "${LABEL:0:3}" == "osx" ]]; then travis_retry brew install ccache ; fi
- if [[ "${LABEL:0:3}" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH" ; fi

script:
- eval $MATRIX_EVAL
# If we're cross compiling aarch64, make sure our build enivornment is setup
# we do this in the script stage because this happens after the repo is cloned
- if [[ "$LABEL" == "aarch64" ]]; then source scripts/prep-aarch64.sh ; fi
- mkdir build && cd build
- cmake -DARCH=default -DCMAKE_BUILD_TYPE=Release -DSTATIC=true ..
- make -j2
- if [[ "$LABEL" != "aarch64" ]]; then ./src/cryptotest ; fi

before_deploy:
- if [[ "${TRAVIS_TAG}" == "" ]]; then export TRAVIS_TAG=${TRAVIS_COMMIT} ; fi
- cd src
- TARGETS="Zentd miner zentwallet Zent-service zentwallet-beta cryptotest wallet-api"
- ${STRIP} ${TARGETS}
- rm -rf ZentCash-${TRAVIS_TAG}
- mkdir ZentCash-${TRAVIS_TAG}
- cp ${TARGETS} ZentCash-${TRAVIS_TAG}/
- cp ../../LICENSE ZentCash-${TRAVIS_TAG}/
- tar cvfz ZentCash-${TRAVIS_TAG}-${LABEL}.tar.gz ZentCash-${TRAVIS_TAG}/
- rm -rf builds
- mkdir builds
- cp ZentCash-${TRAVIS_TAG}-${LABEL}.tar.gz builds
- cd builds

deploy:
  - provider: releases
    api_key:
      secure: rI6m8nLYIZXrC7j6Ki5GJZQZyHM29TB5//exvvpPBCH2vEdi2PBbaLmT6T5oiI/p/OwhPoK1+ma0vb6h2qAxQ7GMbRFuJeJcGdblWzgK42JrM9TcKgzzWDKON2a6SyeyB2UdfuIiY/qE8H4SSEGbjUt3z7ZWha6877SW8lD4nx7FSm6yYjvs4KTieNgRIhHYg4NQQgXwtRhz5voyf14B12RlmMnwztjoJrqobPUicxRi1wARPCwisnP/FUuqngdErjV5/pK1mIYRsmr/BeNxDseuZBMTfYiU4JMtL30T0FevQ88Ex+hig3bBEYjpvB0raHqlgwKRFhMXJwN31f96iGYCB5+H9GnAelX0qEpoxu3ffBoChsAixSWAsJxSXK3T2gavlr2iQndaTAhEmAsZu/agKfMXu/uBx0egG+36ivhlytXH7IqXRnHMrEEjU8O1XfNKrzjAcYHTKFIpAUSwhf+v1klnmlIksUBjh5goEklt06Y22SJr7layLvDchp51h88QaMsWNpo8LcJ7HRDyH0FvZMmL2xsoqZ40cHeDkSCUeLCK1ffKqsNU6KeIvF1GUbu8sH9mENqKlQDfPTg2n8ftooP27G9khBW5rpK12YqMHrqKZFCtzG0iP9l9pCObSuDpAK7O7uhbsAb9/J4TIXyoN8MysDqLFe58DKW88oE=
    file:
      - ZentCash-${TRAVIS_TAG}-${LABEL}.tar.gz
    on:
      repo: ZentCashFoundation/Zent
      tags: true
      condition: "$_DEPLOYABLE = true"
